[backup]
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]
git-ignore = true
no-require-git = true

[[backup.snapshots]]
sources = ["/home/adrien"]
globs = ["!/home/adrien/.*"]
one-file-system = true

[[backup.snapshots]]
sources = ["/home/adrien/.ssh/config"]
one-file-system = true
skip-identical-parent = true

[forget]
keep-within-hourly = "7 days"
keep-within-daily = "1 month"
keep-within-monthly = "3 years"
keep-within-half-yearly = "10 years"
