[global]
log-level = "warn"
use-profiles = ["home-source"]

[repository]
repository = "opendal:sftp"
password-command = "secret-tool lookup rustic-backup manwe-hdd"

[repository.options]
user = "adrien"
endpoint = "100.81.95.30"
root = "/mnt/backup-hdd/adrien/backup/rustic-repo"
