#! /bin/sh

bspc config bottom_padding      24
bspc config border_width        0
bspc config window_gap          2

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d 01 02 03 04 05 06 07 08 09 10

bspc rule -a Gimp desktop=^8 follow=on floating=on

xsetroot -cursor_name left_ptr &
feh --no-fehbg --bg-fill -z .walls/*
nm-applet &
volumeicon &
sleep 1 && tint2 &
