add_newline = false
format = """
$username$hostname \
$directory\
$git_branch$git_commit$git_state$git_status\
$hg_branch\
$cmake$python$rust\
$custom\
$cmd_duration\
$line_break\
$status$character"""

[username]
style_user = "yellow"
format = "[$user]($style)"

[hostname]
style = "yellow"
format = "[@$hostname]($style)"

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "…/"
read_only = " "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
style = "yellow"
conflicted = "=${count}"
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "﫧${count}"
format = "([$ahead_behind$all_status]($style) )"

[hg_branch]
symbol = " "

[cmake]
symbol = "卑"
format = "[$symbol($version )]($style)"

[python]
symbol = " "
python_binary = ["python3", "python", "python2"]
format = "[${symbol}${pyenv_prefix}(${version} )($virtualenv )]($style)"

[rust]
symbol = " "
format = "[$symbol($version )]($style)"

[cmd_duration]
format = "[ $duration]($style) "
